## 3. A grading assistant

Teachers in general have a lot of administrations to do and one of those things is grading. Can we create a simple grade assistant to assist a Swedish teacher in grading? This exercise focuses a lot in prompt engineering and afterwards to postprocess the output using Pydantic.

a) Go into this page with examples of students answers to a particular question. Copy some example texts and paste it into files with names like `student_text_1.txt`, `student_text_2.txt`.

b) Read these data into python and tell your LLM to grade them.

In [4]:
path = "student_answers/student_text"

student_answers = []
for i in range(1,3):
    with open(f"{path}{i}.txt", "r", encoding="utf-8") as file:
        student_answers.append(file.read())
student_answers

['Inför allas blickar\nEn av de större andledningarna att man är tal rädd är förmodligen att man är\nrädd för att folket som lyssnar på kommer göra narr av en. När man är ensam\npå en scen eller i klass rummet så är det väldigt jobbigt när det sitter ett flertal\nmänniskor som sitter och tittar på en. Jag känner mig inte så säker när jag står och\ngör en föreläsning eller en presentation. Känslan när man är framför människor\nsom man inte riktigt känner är ganska obehagligt, för man vill inte att dem ska\ntycka illa om en, eller tycka att man är konstig på något vis. Men jag tror att det\ngår att bli av med talrädslan, om man börjar i en mindre grupp och gör sig vann\nmed att prata med människor utan att bli rädd eller känna obehag.\nPeter Letmark skriver i Dagens Nyheter 2012-05-04 att det har att göra med\nevolutionära förklaringar, att man är rädd för ormar eller hundar kan ju vara\nen sak som sitter i ryggmärgen. Det kan bero på att man är rädd för att bli\nutstöt från gruppen. Letmark berättar även att primater organiserar sitt sociala\nliv i hierarkier. Rädslan för att prata i grupp kanske gör att man undviker\ndominanskonflikter. Det Letmark skriver låter ganska rimligt, mina åsikter är\nnästan desamma. Jag tror att det är lättare att prata om något som sitter nära ditt\nhjärta, för att då brinner du för det du pratar om och kan fortsätta väldigt enkelt\nutan att inte veta vad du ska prata om. Om det är något du inte tycker är så\nintressant men måste prata om det av jobb skäl, så blir det nog betydligt svårare.\nMen det blir garanterat lättare om du har bra själv förtroende, dom som har\nlite sämre själv förtroende blir du väldigt osäker på vad du säger och vågar inte\nargumentera om din åsikt.',
 'Inför allas blickar\nAtt ha muntliga presentationer är något som uppleves skrämmande i dagens\nsamhälle för att vi lever i ett samhälle där man oftast inte blir tvingade till att\ngöra något. Muntliga presentationer är något man, i de flesta fall brukar bli\ntvungen att göra i skolan först. Det händer när man är i den åldern då man\ntänker väldigt mycket på vad ens vänner tycker om en. Så att behöva stå framför\nde och presentera något kan kännas skrämmande för då tror man att de som\ntittar på dig dömer dig. Vilket blir något som fastar med en även när man blir\näldre. Muntliga presentationer är inte något man gör i skolan lika ofta som att\nlämna in en uppgift så man blir aldrig riktigt van med det. Att bli van med att\ntala framför andra är ett bra sätt att bota talängslan. Desto mer man pratar inför\nen grupp människor ju mer inser man att det inte är så farligt och man kommer\nsäkert komma på några knep på att kunna hantera sina nerver om man börjar att\nprata inför andra mycket mer. I artikeln ” därför blir vi skräckslagna” av Peter\nLetmark i DN, skriver Letmark om hur att prata inför andra var en gång i tiden\nen bra och viktigt egenskap att ha, men att dagens informationssamhälle har\ngjort det svårare och att tala inför en grupp.\nDet har blivit den vanligast rädslan för människor. Letmark skriver att rädslan\nför att tala inför grupper existerar i människor för att inte bli utstött från en viss\ngrupp. Att man inte vågade träda fram och ta plast för i tiden för att inte bli\nutstött i gruppen vilket hotade ens överlevnads chanser. Letmark skriver också\nom att man kan ärva rädslan om att tala inför grupper vilket vi människor i dag\nkan ha ärvt från våra förfäder, som undvek att ta plast i gruppen med rädslan\nav att bli utstöt. Konsekvenserna av detta är att samhället inte kommer att\nkunna utvecklas om människorna i vårt samhälle är för rädda för att ta plast\noch utrycka sig. Som jag skrev tidigare är det bra med att det blir en van att tala\ninför grupper. Letmark skriver i artikeln att man kan träna sig i små steg med att\ngöra det en vana. Man kan bara börja med att prata med sig själv framför spegel\noch sen öka publiken lite åt taget. Det viktigaste är att göra det en del av sitt\nvardagliga liv så att man verkligen måste prestera så är allting inte som en chock.']

load gemini client with api key

In [5]:
from google import genai
from dotenv import load_dotenv
import os

load_dotenv()
client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

## utan betygskriterier

c) Prompt to get an output of fields proposed_grade, motivation and improvements.

In [6]:
prompt = f"""
    Du är en betygsättnings assistant och ska försöka underlätta för läraren i Svenska 1.
    Betygsätt dessa texter mellan F-A ['F', 'E', 'D', 'C' 'B', 'A'], där 'F' är det lägsta betyget, och 'A' är det högsta betyget): {student_answers}
    
    För varje text, lägg till texten som betygsätts i fältet: student_answer
    
    Jag vill ha output i detta format och dessa fält:
    {{
        student_answer: str,
        proposed_grade: char F-A,
        motivation: str 'motivering till betyget',
        improvements: str 'saker som kan förbättras för att nå ett högre betyg
    }}
    
    Output ska vara endast i json-format.
    INTE markdown.
    Texter: 
    {student_answers}
"""

response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)

print(response.text)

[
  {
    "student_answer": "Inför allas blickar\nEn av de större andledningarna att man är tal rädd är förmodligen att man är\nrädd för att folket som lyssnar på kommer göra narr av en. När man är ensam\npå en scen eller i klass rummet så är det väldigt jobbigt när det sitter ett flertal\nmänniskor som sitter och tittar på en. Jag känner mig inte så säker när jag står och\ngör en föreläsning eller en presentation. Känslan när man är framför människor\nsom man inte riktigt känner är ganska obehagligt, för man vill inte att dem ska\ntycka illa om en, eller tycka att man är konstig på något vis. Men jag tror att det\ngår att bli av med talrädslan, om man börjar i en mindre grupp och gör sig vann\nmed att prata med människor utan att bli rädd eller känna obehag.\nPeter Letmark skriver i Dagens Nyheter 2012-05-04 att det har att göra med\nevolutionära förklaringar, att man är rädd för ormar eller hundar kan ju vara\nen sak som sitter i ryggmärgen. Det kan bero på att man är rädd för att bli\nutstöt från gruppen. Letmark berättar även att primater organiserar sitt sociala\nliv i hierarkier. Rädslan för att prata i grupp kanske gör att man undviker\ndominanskonflikter. Det Letmark skriver låter ganska rimligt, mina åsikter är\nnästan desamma. Jag tror att det är lättare att prata om något som sitter nära ditt\nhjärta, för att då brinner du för det du pratar om och kan fortsätta väldigt enkelt\nutan att inte veta vad du ska prata om. Om det är något du inte tycker är så\nintressant men måste prata om det av jobb skäl, så blir det nog betydligt svårare.\nMen det blir garanterat lättare om du har bra själv förtroende, dom som har\nlite sämre själv förtroende blir du väldigt osäker på vad du säger och vågar inte\nargumentera om din åsikt.",
    "proposed_grade": "E",
    "motivation": "Texten tar upp ett relevant ämne och presenterar både egna reflektioner och referenser till en källa. Innehållet är grundläggande och visar en viss förståelse för ämnet. Dock är texten genomgående präglad av ett stort antal språkliga fel som allvarligt stör läsningen och sänker kvaliteten. Detta inkluderar frekventa fel i stavning (t.ex. 'andledningarna', 'tal rädd', 'klass rummet', 'själv förtroende', 'vann'), inkonsekvent användning av 'dem' och 'de' samt 'dom', och omständliga eller grammatiskt inkorrekta formuleringar (t.ex. 'utan att inte veta', 'blir du väldigt osäker').",
    "improvements": "Fokusera på grundläggande språklig korrekthet: öva på sammansatta ord (t.ex. 'talrädd', 'klassrummet', 'självförtroende', 'jobbskäl'), repetera regler för 'de/dem' och undvik 'dom' i skrift. Kontrollera meningsbyggnad för att undvika dubbla negationer och krångliga formuleringar. Använd stavningskontroll noggrant. För att förbättra innehållet, sträva efter att integrera källmaterialet på ett mer analytiskt sätt, bortom att bara återberätta eller instämma, och utveckla egna argument i större utsträckning. Se också över sambandet mellan de olika delarna i texten för ett bättre flyt."
  },
  {
    "student_answer": "Inför allas blickar\nAtt ha muntliga presentationer är något som uppleves skrämmande i dagens\nsamhälle för att vi lever i ett samhälle där man oftast inte blir tvingade till att\ngöra något. Muntliga presentationer är något man, i de flesta fall brukar bli\ntvungen att göra i skolan först. Det händer när man är i den åldern då man\ntänker väldigt mycket på vad ens vänner tycker om en. Så att behöva stå framför\nde och presentera något kan kännas skrämmande för då tror man att de som\ntittar på dig dömer dig. Vilket blir något som fastar med en även när man blir\näldre. Muntliga presentationer är inte något man gör i skolan lika ofta som att\nlämna in en uppgift så man blir aldrig riktigt van med det. Att bli van med att\ntala framför andra är ett bra sätt att bota talängslan. Desto mer man pratar inför\nen grupp människor ju mer inser man att det inte är så farligt och man kommer\nsäkert komma på några knep på att kunna hantera sina nerver om man börjar att\nprata inför andra mycket mer. I artikeln ” därför blir vi skräckslagna” av Peter\nLetmark i DN, skriver Letmark om hur att prata inför andra var en gång i tiden\nen bra och viktigt egenskap att ha, men att dagens informationssamhälle har\ngjort det svårare och att tala inför en grupp.\nDet har blivit den vanligast rädslan för människor. Letmark skriver att rädslan\nför att tala inför grupper existerar i människor för att inte bli utstött från en viss\ngrupp. Att man inte vågade träda fram och ta plast för i tiden för att inte bli\nutstött i gruppen vilket hotade ens överlevnads chanser. Letmark skriver också\nom att man kan ärva rädslan om att tala inför grupper vilket vi människor i dag\nkan ha ärvt från våra förfäder, som undvek att ta plast i gruppen med rädslan\nav att bli utstöt. Konsekvenserna av detta är att samhället inte kommer att\nkunna utvecklas om människorna i vårt samhälle är för rädda för att ta plast\noch utrycka sig. Som jag skrev tidigare är det bra med att det blir en van att tala\ninför grupper. Letmark skriver i artikeln att man kan träna sig i små steg med att\ngöra det en vana. Man kan bara börja med att prata med sig själv framför spegel\noch sen öka publiken lite åt taget. Det viktigaste är att göra det en del av sitt\nvärdagliga liv så att man verkligen måste prestera så är allting inte som en chock.",
    "proposed_grade": "C",
    "motivation": "Texten presenterar ett tydligt och relevant innehåll med en välstrukturerad uppbyggnad. Eleven för en relativt sammanhållen argumentation där egna reflektioner kopplas till Letmarks artikel på ett bra sätt. Analysen av källan är mer utvecklad än i den första texten, med en diskussion om både orsaker, konsekvenser och lösningar. Texten visar förståelse för ämnet och kan resonera kring det. Dock finns det fortfarande språkliga brister, såsom felaktig passivform ('uppleves'), konsekventa stavfel ('ta plast' istället för 'ta plats'), samt en del omständliga meningar och viss inkonsekvens i bruket av 'de/dem'. Dessa fel stör läsflödet men är inte lika genomgripande som i den första texten.",
    "improvements": "Arbeta systematiskt med de kvarvarande språkliga felen, särskilt stavfel som 'ta plast' (ska vara 'ta plats'), 'överlevnads chanser' (ska vara 'överlevnadschanser'), 'utstöt' (ska vara 'utstött') och grammatiska fel som 'uppleves' (ska vara 'upplevs'). Öva på meningsbyggnad för att skapa mer koncisa och flytande meningar, särskilt vid längre resonemang. Repetera regler för de/dem. För att nå ett högre betyg kan eleven fördjupa analysen ytterligare, till exempel genom att kritiskt granska Letmarks perspektiv, jämföra med andra förklaringsmodeller eller utveckla den egna argumentationens komplexitet. Variera ordförrådet och meningsbyggnaden ytterligare för att uppnå en mer nyanserad och akademisk stil."
  }
]

d) Now validate this with pydantic model

In [7]:
from pydantic import BaseModel, ValidationError
from typing import Literal, List
import json

class Grade(BaseModel):
    student_answer: str
    proposed_grade: Literal['F', 'E', 'D', 'C', 'B', 'A']
    motivation: str
    improvements: str

class GradeListResponse(BaseModel):
    results: List[Grade]

response.text.replace("\n", " ")
stripped_response = response.text.replace("json", "").strip("```")
data = json.loads(stripped_response)

grades = []
for grade in data:
    try:
        grades.append(Grade.model_validate(grade))
    except ValidationError as err:
        print(err)

grade_response_without_criterias = GradeListResponse(results=grades)
print(grade_response_without_criterias.model_dump())

{'results': [{'student_answer': 'Inför allas blickar\nEn av de större andledningarna att man är tal rädd är förmodligen att man är\nrädd för att folket som lyssnar på kommer göra narr av en. När man är ensam\npå en scen eller i klass rummet så är det väldigt jobbigt när det sitter ett flertal\nmänniskor som sitter och tittar på en. Jag känner mig inte så säker när jag står och\ngör en föreläsning eller en presentation. Känslan när man är framför människor\nsom man inte riktigt känner är ganska obehagligt, för man vill inte att dem ska\ntycka illa om en, eller tycka att man är konstig på något vis. Men jag tror att det\ngår att bli av med talrädslan, om man börjar i en mindre grupp och gör sig vann\nmed att prata med människor utan att bli rädd eller känna obehag.\nPeter Letmark skriver i Dagens Nyheter 2012-05-04 att det har att göra med\nevolutionära förklaringar, att man är rädd för ormar eller hundar kan ju vara\nen sak som sitter i ryggmärgen. Det kan bero på att man är rädd för att bli\nutstöt från gruppen. Letmark berättar även att primater organiserar sitt sociala\nliv i hierarkier. Rädslan för att prata i grupp kanske gör att man undviker\ndominanskonflikter. Det Letmark skriver låter ganska rimligt, mina åsikter är\nnästan desamma. Jag tror att det är lättare att prata om något som sitter nära ditt\nhjärta, för att då brinner du för det du pratar om och kan fortsätta väldigt enkelt\nutan att inte veta vad du ska prata om. Om det är något du inte tycker är så\nintressant men måste prata om det av jobb skäl, så blir det nog betydligt svårare.\nMen det blir garanterat lättare om du har bra själv förtroende, dom som har\nlite sämre själv förtroende blir du väldigt osäker på vad du säger och vågar inte\nargumentera om din åsikt.', 'proposed_grade': 'E', 'motivation': "Texten tar upp ett relevant ämne och presenterar både egna reflektioner och referenser till en källa. Innehållet är grundläggande och visar en viss förståelse för ämnet. Dock är texten genomgående präglad av ett stort antal språkliga fel som allvarligt stör läsningen och sänker kvaliteten. Detta inkluderar frekventa fel i stavning (t.ex. 'andledningarna', 'tal rädd', 'klass rummet', 'själv förtroende', 'vann'), inkonsekvent användning av 'dem' och 'de' samt 'dom', och omständliga eller grammatiskt inkorrekta formuleringar (t.ex. 'utan att inte veta', 'blir du väldigt osäker').", 'improvements': "Fokusera på grundläggande språklig korrekthet: öva på sammansatta ord (t.ex. 'talrädd', 'klassrummet', 'självförtroende', 'jobbskäl'), repetera regler för 'de/dem' och undvik 'dom' i skrift. Kontrollera meningsbyggnad för att undvika dubbla negationer och krångliga formuleringar. Använd stavningskontroll noggrant. För att förbättra innehållet, sträva efter att integrera källmaterialet på ett mer analytiskt sätt, bortom att bara återberätta eller instämma, och utveckla egna argument i större utsträckning. Se också över sambandet mellan de olika delarna i texten för ett bättre flyt."}, {'student_answer': 'Inför allas blickar\nAtt ha muntliga presentationer är något som uppleves skrämmande i dagens\nsamhälle för att vi lever i ett samhälle där man oftast inte blir tvingade till att\ngöra något. Muntliga presentationer är något man, i de flesta fall brukar bli\ntvungen att göra i skolan först. Det händer när man är i den åldern då man\ntänker väldigt mycket på vad ens vänner tycker om en. Så att behöva stå framför\nde och presentera något kan kännas skrämmande för då tror man att de som\ntittar på dig dömer dig. Vilket blir något som fastar med en även när man blir\näldre. Muntliga presentationer är inte något man gör i skolan lika ofta som att\nlämna in en uppgift så man blir aldrig riktigt van med det. Att bli van med att\ntala framför andra är ett bra sätt att bota talängslan. Desto mer man pratar inför\nen grupp människor ju mer inser man att det inte är så farligt och man kommer\nsäkert komma på några knep på att kunna hantera sina nerver om man börjar att\nprata inför andra mycket mer. I artikeln ” därför blir vi skräckslagna” av Peter\nLetmark i DN, skriver Letmark om hur att prata inför andra var en gång i tiden\nen bra och viktigt egenskap att ha, men att dagens informationssamhälle har\ngjort det svårare och att tala inför en grupp.\nDet har blivit den vanligast rädslan för människor. Letmark skriver att rädslan\nför att tala inför grupper existerar i människor för att inte bli utstött från en viss\ngrupp. Att man inte vågade träda fram och ta plast för i tiden för att inte bli\nutstött i gruppen vilket hotade ens överlevnads chanser. Letmark skriver också\nom att man kan ärva rädslan om att tala inför grupper vilket vi människor i dag\nkan ha ärvt från våra förfäder, som undvek att ta plast i gruppen med rädslan\nav att bli utstöt. Konsekvenserna av detta är att samhället inte kommer att\nkunna utvecklas om människorna i vårt samhälle är för rädda för att ta plast\noch utrycka sig. Som jag skrev tidigare är det bra med att det blir en van att tala\ninför grupper. Letmark skriver i artikeln att man kan träna sig i små steg med att\ngöra det en vana. Man kan bara börja med att prata med sig själv framför spegel\noch sen öka publiken lite åt taget. Det viktigaste är att göra det en del av sitt\nvärdagliga liv så att man verkligen måste prestera så är allting inte som en chock.', 'proposed_grade': 'C', 'motivation': "Texten presenterar ett tydligt och relevant innehåll med en välstrukturerad uppbyggnad. Eleven för en relativt sammanhållen argumentation där egna reflektioner kopplas till Letmarks artikel på ett bra sätt. Analysen av källan är mer utvecklad än i den första texten, med en diskussion om både orsaker, konsekvenser och lösningar. Texten visar förståelse för ämnet och kan resonera kring det. Dock finns det fortfarande språkliga brister, såsom felaktig passivform ('uppleves'), konsekventa stavfel ('ta plast' istället för 'ta plats'), samt en del omständliga meningar och viss inkonsekvens i bruket av 'de/dem'. Dessa fel stör läsflödet men är inte lika genomgripande som i den första texten.", 'improvements': "Arbeta systematiskt med de kvarvarande språkliga felen, särskilt stavfel som 'ta plast' (ska vara 'ta plats'), 'överlevnads chanser' (ska vara 'överlevnadschanser'), 'utstöt' (ska vara 'utstött') och grammatiska fel som 'uppleves' (ska vara 'upplevs'). Öva på meningsbyggnad för att skapa mer koncisa och flytande meningar, särskilt vid längre resonemang. Repetera regler för de/dem. För att nå ett högre betyg kan eleven fördjupa analysen ytterligare, till exempel genom att kritiskt granska Letmarks perspektiv, jämföra med andra förklaringsmodeller eller utveckla den egna argumentationens komplexitet. Variera ordförrådet och meningsbyggnaden ytterligare för att uppnå en mer nyanserad och akademisk stil."}]}

In [8]:
import pandas as pd
without_criterias = [grade.model_dump() for grade in grades]
# without_criterias = without_criterias["results"]
df_grades_without_criteras = pd.DataFrame(without_criterias)
df_grades_without_criteras

,student_answer,proposed_grade,motivation,improvements
0,Inför allas blickar\nEn av de större andlednin...,E,Texten tar upp ett relevant ämne och presenter...,Fokusera på grundläggande språklig korrekthet:...
1,Inför allas blickar\nAtt ha muntliga presentat...,C,Texten presenterar ett tydligt och relevant in...,Arbeta systematiskt med de kvarvarande språkli...

e) Output a folder with the following txt files: proposed_grade.txt, motivation.txt and improvements.txt

In [9]:
folder = "grade_outputs1"
os.makedirs(folder, exist_ok=True)

files = {
    "proposed_grade_without_criterias.txt": "proposed_grade",
    "motivation_without_criterias.txt": "motivation", 
    "improvements_without_criterias.txt": "improvements"
    }

for filename, field in files.items():
    with open(f"{folder}/{filename}", "w", encoding="utf-8") as file:
        for grade in grade_response_without_criterias.results:
            value = getattr(grade, field)
            file.write(value + "\n\n")

## med betygskriterier

f) Go [into skolverket for Svenska 1](https://www.skolverket.se/undervisning/gymnasieskolan/program-och-amnen-i-gymnasieskolan/hitta-program-amnen-och-kurser-i-gymnasieskolan-gy11/amne?url=907561864%2Fsyllabuscw%2Fjsp%2Fsubject.htm%3FsubjectCode%3DSVE%26version%3D8%26tos%3Dgy&sv.url=12.5dfee44715d35a5cdfa92a3) and copy "Betygskriterier" for "Svenska 1". These are the criterias for the different grades. Paste this into a file called `criterias.txt`.

c) Prompt to get an output of fields proposed_grade, motivation and improvements.

In [10]:
folder_path = "student_answers"

with open(f"{folder_path}/criterias.txt", "r", encoding="utf-8") as file:
    criterias = file.read()

prompt = f"""
    Du är en betygsättnings assistant och ska försöka underlätta för läraren i Svenska 1.
    Baserat på dessa betygskriterier: {criterias}
    
    För varje text, lägg till texten som betygsätts i fältet: student_answer
    
    Jag vill ha output i detta format och dessa fält:
    {{
        student_answer: str,
        proposed_grade: char F-A,
        motivation: str 'motivering till betyget',
        improvements: str 'saker som kan förbättras för att nå ett högre betyg
    }}
    
    Output ska vara endast i json-format.
    INTE markdown.
    Betygsätt dessa texter: {student_answers} 
"""

response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)

print(response.text)

```json
[
    {
        "student_answer": "Inför allas blickar\nEn av de större andledningarna att man är tal rädd är förmodligen att man är\nrädd för att folket som lyssnar på kommer göra narr av en. När man är ensam\npå en scen eller i klass rummet så är det väldigt jobbigt när det sitter ett flertal\nmänniskor som sitter och tittar på en. Jag känner mig inte så säker när jag står och\ngör en föreläsning eller en presentation. Känslan när man är framför människor\nsom man inte riktigt känner är ganska obehagligt, för man vill inte att dem ska\ntycka illa om en, eller tycka att man är konstig på något vis. Men jag tror att det\ngår att bli av med talrädslan, om man börjar i en mindre grupp och gör sig vann\nmed att prata med människor utan att bli rädd eller känna obehag.\nPeter Letmark skriver i Dagens Nyheter 2012-05-04 att det har att göra med\nevolutionära förklaringar, att man är rädd för ormar eller hundar kan ju vara\nen sak som sitter i ryggmärgen. Det kan bero på att man är rädd för att bli\nutstöt från gruppen. Letmark berättar även att primater organiserar sitt sociala\nliv i hierarkier. Rädslan för att prata i grupp kanske gör att man undviker\ndominanskonflikter. Det Letmark skriver låter ganska rimligt, mina åsikter är\nnästan desamma. Jag tror att det är lättare att prata om något som sitter nära ditt\nhjärta, för att då brinner du för det du pratar om och kan fortsätta väldigt enkelt\nutan att inte veta vad du ska prata om. Om det är något du inte tycker är så\nintressant men måste prata om det av jobb skäl, så blir det nog betydligt svårare.\nMen det blir garanterat lättare om du har bra själv förtroende, dom som har\nlite sämre själv förtroende blir du väldigt osäker på vad du säger och vågar inte\nargumentera om din åsikt.",
        "proposed_grade": "E",
        "motivation": "Texten är sammanhängande och begriplig, och eleven förmedlar egna tankar och åsikter som anknyter till det lästa materialet. Referensen till Peter Letmark är inkluderad på ett grundläggande sätt, vilket uppfyller kravet på enkel referatteknik för E-nivå. Dock finns det betydande brister i språkriktigheten, såsom frekventa stavfel (t.ex. \"tal rädd\", \"andledningarna\", \"klass rummet\", \"jobb skäl\", \"själv förtroende\"), särskrivningar och enklare meningsbyggnad. Språket är endast till viss del anpassat till syfte och mottagare, med en del informella formuleringar. Dispositionen är inte tydligt urskiljbar, och reflektionerna är enkla.",
        "improvements": "För att nå ett högre betyg behöver eleven fokusera på språkriktighet genom att noggrant korrekturläsa för att åtgärda stavfel, särskrivningar och grammatiska fel. Textens disposition kan förbättras genom en tydligare struktur med en introduktion, en mer utvecklad argumentation i brödtexten och en sammanfattande slutsats. Språket behöver anpassas bättre till syfte och mottagare genom att sträva efter ett mer formellt och akademiskt uttryckssätt. Reflektionerna kan fördjupas och utvecklas mer nyanserat, till exempel genom att förklara *varför* en källa är rimlig istället för att bara konstatera det."
    },
    {
        "student_answer": "Inför allas blickar\nAtt ha muntliga presentationer är något som uppleves skrämmande i dagens\nsamhälle för att vi lever i ett samhälle där man oftast inte blir tvingade till att\ngöra något. Muntliga presentationer är något man, i de flesta fall brukar bli\ntvungen att göra i skolan först. Det händer när man är i den åldern då man\ntänker väldigt mycket på vad ens vänner tycker om en. Så att behöva stå framför\nde och presentera något kan kännas skrämmande för då tror man att de som\ntittar på dig dömer dig. Vilket blir något som fastar med en även när man blir\näldre. Muntliga presentationer är inte något man gör i skolan lika ofta som att\nlämna in en uppgift så man blir aldrig riktigt van med det. Att bli van med att\ntala framför andra är ett bra sätt att bota talängslan. Desto mer man pratar inför\nen grupp människor ju mer inser man att det inte är så farligt och man kommer\nsäkert komma på några knep på att kunna hantera sina nerver om man börjar att\nprata inför andra mycket mer. I artikeln ” därför blir vi skräckslagna” av Peter\nLetmark i DN, skriver Letmark om hur att prata inför andra var en gång i tiden\nen bra och viktigt egenskap att ha, men att dagens informationssamhälle har\ngjort det svårare och att tala inför en grupp.\nDet har blivit den vanligast rädslan för människor. Letmark skriver att rädslan\nför att tala inför grupper existerar i människor för att inte bli utstött från en viss\ngrupp. Att man inte vågade träda fram och ta plast för i tiden för att inte bli\nutstött i gruppen vilket hotade ens överlevnads chanser. Letmark skriver också\nom att man kan ärva rädslan om att tala inför grupper vilket vi människor i dag\nkan ha ärvt från våra förfäder, som undvek att ta plast i gruppen med rädslan\nav att bli utstöt. Konsekvenserna av detta är att samhället inte kommer att\nkunna utvecklas om människorna i vårt samhälle är för rädda för att ta plast\noch utrycka sig. Som jag skrev tidigare är det bra med att det blir en van att tala\ninför grupper. Letmark skriver i artikeln att man kan träna sig i små steg med att\ngöra det en vana. Man kan bara börja med att prata med sig själv framför spegel\noch sen öka publiken lite åt taget. Det viktigaste är att göra det en del av sitt\nvardagliga liv så att man verkligen måste prestera så är allting inte som en chock.",
        "proposed_grade": "D",
        "motivation": "Texten är sammanhängande och begriplig med en tydligt urskiljbar disposition. Eleven integrerar egna tankar och reflektioner på ett mer utvecklat sätt än enkla sammanfattningar genom att koppla talrädslan till bredare samhälleliga konsekvenser. Referenserna till källan är väl integrerade och följer grundläggande regler för referatteknik. Språket är till stor del anpassat till syfte och mottagare. Dock förekommer det återkommande brister i språkriktigheten (t.ex. \"uppleves\" istället för \"upplevs\", upprepade fel som \"ta plast\" istället för \"ta plats\", \"överlevnads chanser\") som påverkar helhetsintrycket och hindrar språket från att vara konsekvent varierat och välformulerat, vilket krävs för ett C-betyg.",
        "improvements": "För att uppnå ett högre betyg, som C, behöver eleven arbeta med att förbättra språkriktigheten genom noggrann korrekturläsning av hela texten, särskilt avseende grammatik och stavning av återkommande fel. Det är viktigt att säkerställa att språket i huvudsak följer skriftspråkets normer. Vidare kan språket göras mer varierat och välformulerat genom att experimentera med olika meningsbyggnader och ett bredare ordförråd, samt undvika upprepningar i formuleringarna. Reflektionerna om samhällsutvecklingens konsekvenser kan fördjupas ytterligare med mer konkreta exempel eller genom att diskutera ämnet från flera perspektiv."
    }
]
```

d) Now validate this with pydantic model

In [ ]:
class Grade(BaseModel):
    student_answer: str
    proposed_grade: Literal['F', 'E', 'D', 'C', 'B', 'A']
    motivation: str
    improvements: str

class GradeListResponse(BaseModel):
    results: List[Grade]

stripped_response = response.text.replace("json", "").strip("```")
data = json.loads(stripped_response)

grades = []
for grade in data:
    try:
        grades.append(Grade.model_validate(grade))
    except ValidationError as err:
        print(err)

grade_response_with_criterias = GradeListResponse(results=grades)
print(grade_response_with_criterias.model_dump())

[Grade(student_answer='Inför allas blickar\nEn av de större andledningarna att man är tal rädd är förmodligen att man är\nrädd för att folket som lyssnar på kommer göra narr av en. När man är ensam\npå en scen eller i klass rummet så är det väldigt jobbigt när det sitter ett flertal\nmänniskor som sitter och tittar på en. Jag känner mig inte så säker när jag står och\ngör en föreläsning eller en presentation. Känslan när man är framför människor\nsom man inte riktigt känner är ganska obehagligt, för man vill inte att dem ska\ntycka illa om en, eller tycka att man är konstig på något vis. Men jag tror att det\ngår att bli av med talrädslan, om man börjar i en mindre grupp och gör sig vann\nmed att prata med människor utan att bli rädd eller känna obehag.\nPeter Letmark skriver i Dagens Nyheter 2012-05-04 att det har att göra med\nevolutionära förklaringar, att man är rädd för ormar eller hundar kan ju vara\nen sak som sitter i ryggmärgen. Det kan bero på att man är rädd för att bli\nutstöt från gruppen. Letmark berättar även att primater organiserar sitt sociala\nliv i hierarkier. Rädslan för att prata i grupp kanske gör att man undviker\ndominanskonflikter. Det Letmark skriver låter ganska rimligt, mina åsikter är\nnästan desamma. Jag tror att det är lättare att prata om något som sitter nära ditt\nhjärta, för att då brinner du för det du pratar om och kan fortsätta väldigt enkelt\nutan att inte veta vad du ska prata om. Om det är något du inte tycker är så\nintressant men måste prata om det av jobb skäl, så blir det nog betydligt svårare.\nMen det blir garanterat lättare om du har bra själv förtroende, dom som har\nlite sämre själv förtroende blir du väldigt osäker på vad du säger och vågar inte\nargumentera om din åsikt.', proposed_grade='E', motivation='Texten är sammanhängande och begriplig, och eleven förmedlar egna tankar och åsikter som anknyter till det lästa materialet. Referensen till Peter Letmark är inkluderad på ett grundläggande sätt, vilket uppfyller kravet på enkel referatteknik för E-nivå. Dock finns det betydande brister i språkriktigheten, såsom frekventa stavfel (t.ex. "tal rädd", "andledningarna", "klass rummet", "jobb skäl", "själv förtroende"), särskrivningar och enklare meningsbyggnad. Språket är endast till viss del anpassat till syfte och mottagare, med en del informella formuleringar. Dispositionen är inte tydligt urskiljbar, och reflektionerna är enkla.', improvements='För att nå ett högre betyg behöver eleven fokusera på språkriktighet genom att noggrant korrekturläsa för att åtgärda stavfel, särskrivningar och grammatiska fel. Textens disposition kan förbättras genom en tydligare struktur med en introduktion, en mer utvecklad argumentation i brödtexten och en sammanfattande slutsats. Språket behöver anpassas bättre till syfte och mottagare genom att sträva efter ett mer formellt och akademiskt uttryckssätt. Reflektionerna kan fördjupas och utvecklas mer nyanserat, till exempel genom att förklara *varför* en källa är rimlig istället för att bara konstatera det.'),
 Grade(student_answer='Inför allas blickar\nAtt ha muntliga presentationer är något som uppleves skrämmande i dagens\nsamhälle för att vi lever i ett samhälle där man oftast inte blir tvingade till att\ngöra något. Muntliga presentationer är något man, i de flesta fall brukar bli\ntvungen att göra i skolan först. Det händer när man är i den åldern då man\ntänker väldigt mycket på vad ens vänner tycker om en. Så att behöva stå framför\nde och presentera något kan kännas skrämmande för då tror man att de som\ntittar på dig dömer dig. Vilket blir något som fastar med en även när man blir\näldre. Muntliga presentationer är inte något man gör i skolan lika ofta som att\nlämna in en uppgift så man blir aldrig riktigt van med det. Att bli van med att\ntala framför andra är ett bra sätt att bota talängslan. Desto mer man pratar inför\nen grupp människor ju mer inser man att det inte är så farligt och man kommer\nsäkert komma på några knep på att kunna hantera sina nerver om man börjar att\nprata inför andra mycket mer. I artikeln ” därför blir vi skräckslagna” av Peter\nLetmark i DN, skriver Letmark om hur att prata inför andra var en gång i tiden\nen bra och viktigt egenskap att ha, men att dagens informationssamhälle har\ngjort det svårare och att tala inför en grupp.\nDet har blivit den vanligast rädslan för människor. Letmark skriver att rädslan\nför att tala inför grupper existerar i människor för att inte bli utstött från en viss\ngrupp. Att man inte vågade träda fram och ta plast för i tiden för att inte bli\nutstött i gruppen vilket hotade ens överlevnads chanser. Letmark skriver också\nom att man kan ärva rädslan om att tala inför grupper vilket vi människor i dag\nkan ha ärvt från våra förfäder, som undvek att ta plast i gruppen med rädslan\nav att bli utstöt. Konsekvenserna av detta är att samhället inte kommer att\nkunna utvecklas om människorna i vårt samhälle är för rädda för att ta plast\noch utrycka sig. Som jag skrev tidigare är det bra med att det blir en van att tala\ninför grupper. Letmark skriver i artikeln att man kan träna sig i små steg med att\ngöra det en vana. Man kan bara börja med att prata med sig själv framför spegel\noch sen öka publiken lite åt taget. Det viktigaste är att göra det en del av sitt\nvardagliga liv så att man verkligen måste prestera så är allting inte som en chock.', proposed_grade='D', motivation='Texten är sammanhängande och begriplig med en tydligt urskiljbar disposition. Eleven integrerar egna tankar och reflektioner på ett mer utvecklat sätt än enkla sammanfattningar genom att koppla talrädslan till bredare samhälleliga konsekvenser. Referenserna till källan är väl integrerade och följer grundläggande regler för referatteknik. Språket är till stor del anpassat till syfte och mottagare. Dock förekommer det återkommande brister i språkriktigheten (t.ex. "uppleves" istället för "upplevs", upprepade fel som "ta plast" istället för "ta plats", "överlevnads chanser") som påverkar helhetsintrycket och hindrar språket från att vara konsekvent varierat och välformulerat, vilket krävs för ett C-betyg.', improvements='För att uppnå ett högre betyg, som C, behöver eleven arbeta med att förbättra språkriktigheten genom noggrann korrekturläsning av hela texten, särskilt avseende grammatik och stavning av återkommande fel. Det är viktigt att säkerställa att språket i huvudsak följer skriftspråkets normer. Vidare kan språket göras mer varierat och välformulerat genom att experimentera med olika meningsbyggnader och ett bredare ordförråd, samt undvika upprepningar i formuleringarna. Reflektionerna om samhällsutvecklingens konsekvenser kan fördjupas ytterligare med mer konkreta exempel eller genom att diskutera ämnet från flera perspektiv.')]

e) Output a folder with the following txt files: proposed_grade.txt, motivation.txt and improvements.txt

In [12]:
folder = "grade_outputs1"
os.makedirs(folder, exist_ok=True)

files = {
    "proposed_grade_with_criterias.txt": "proposed_grade",
    "motivation_with_criterias.txt": "motivation", 
    "improvements_with_criterias.txt": "improvements"
    }

for filename, field in files.items():
    with open(f"{folder}/{filename}", "w", encoding="utf-8") as file:
        for grade in grade_response_with_criterias.results:
            value = getattr(grade, field)
            file.write(value + "\n\n")

h) Can you improve the output quality by providing few shot examples?

Yes, by giving clear instructions on what type of output you want, and with examples, there will be less validation errors.

## comparison between outputs

In [13]:
import pandas as pd
with_criterias = [grade.model_dump() for grade in grades]
# without_criterias = without_criterias["results"]
df_grades_with_criteras = pd.DataFrame(with_criterias)
df_grades_with_criteras

,student_answer,proposed_grade,motivation,improvements
0,Inför allas blickar\nEn av de större andlednin...,E,"Texten är sammanhängande och begriplig, och el...",För att nå ett högre betyg behöver eleven foku...
1,Inför allas blickar\nAtt ha muntliga presentat...,D,Texten är sammanhängande och begriplig med en ...,"För att uppnå ett högre betyg, som C, behöver ..."

In [14]:
import pandas as pd
# grade_response_with_criterias
grades_dict = {
    "proposed_grade_without_criterias": df_grades_without_criteras["proposed_grade"],
    "proposed_grade_with_criterias": df_grades_with_criteras["proposed_grade"]
}


grades_df = pd.DataFrame(grades_dict)
grades_df

  proposed_grade_without_criterias proposed_grade_with_criterias
0                                E                             E
1                                C                             D